[phases.setup]
nixPkgs = [
  "python310",
  # Для OpenGL/GUI:
  "mesa",           # дає libGL.so.1
  "libglvnd",       # modern OpenGL dispatch
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libXfixes",
  "xorg.libXcursor",
  "xorg.libXi",
  "xorg.libSM",
  "xorg.libXinerama"  # можливо теж знадобиться
]
